// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Users     string
	Total     string
	Discount  string
	Payment   string
	Shipping  string
}

type User struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserOauthID string
	Name        string
	Email       string
}
