// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Users     string `json:"users"`
	Total     string `json:"total"`
	Discount  string `json:"discount"`
	Payment   string `json:"payment"`
	Shipping  string `json:"shipping"`
}
